version: '3'

services:
  db:
    image: postgres:alpine
    env_file: environ.env
    container_name: db
    ports: 
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    # restart: always  
    ports:
      - "8000:8000"
    depends_on:
      - db  
    env_file:
      - environ.env
